#Each new term in the Fibonacci sequence is generated by adding the previous 
#two terms. By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed
#four million, find the sum of the even-valued terms.

def Fibonacci(number):
    Sum = 2
    Fibo = [1 ,2]
    i = 1
    j = 2

    while j <= number:
        #Fibonnaci sequnce
        Fibo.append(Fibo[i] + Fibo[i-1])
        
        #Now 'Fibo[i]' is the new generated member of the list.
        i = i + 1

        #If 'i' is even, add 'Fibo[i]' to 'Sum'.
        if Fibo[i] % 2 == 0:
            Sum = Sum + Fibo[i]

        #In order to the while to work, j is now the last number on the sequence.
        j = Fibo[i]

    return Sum

print(Fibonacci(4000000))